services:
  easthampton:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    image: easthampton-tile
    container_name: easthampton
    ports:
      - "8002:8002"
    env_file:
      - .env.local
    restart: unless-stopped
